### ISSUE TITLE
Cordova App crashes on start

### ISSUE THREAD

**Issue by hypery2k** [MobileChromeApps/cordova-plugin-crosswalk-webview#22]
Following the steps from [Apache Cordova](http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html) I'm getting the following error:

```
[2015-04-17 10:08:56 - xwalk_core_library] Could not find xwalk_core_library.apk!
```

Any ideas?

**Comment by TanaseButcaru** [comment]
I don't know what my log error was, but on diff. devices (Kitkat and Lollipop) + emulator, my app was crashing, but after adding these 3 lines to AndroidManifest solved my problems:
```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
```

**Comment by hypery2k** [comment]
thanks, that helped solving my issue
