### ISSUE TITLE
Add option to download canary version

### ISSUE THREAD

**Issue by Hirbod** [MobileChromeApps/cordova-plugin-crosswalk-webview#24]
Hi,

as I'm using crosswalk's canary version (I need to, because there is an important transparency bug fixed which I need). I need to have the option to specify a canary version.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-%28Android%29

https://download.01.org/crosswalk/releases/crosswalk/android/canary/

**Comment by agrieve** [comment]
Doesn't look like we'll be able to allow Canary since they are not available under the maven repository:

https://download.01.org/crosswalk/releases/crosswalk/android/maven2/

I have just added a `<preference>` for trying out whatever version from there that you want though: 96971b5d098d

**Comment by Hirbod** [comment]
Thanks for your incredible fast work.
So setting the preference to
 <preference name="xwalkVersion" value="xwalk_core_library_beta:13+" > 
would download the lastet canary version? (Or is beta something else than canary?) 
As far as I know, the important patch I need is only inside of the canary >= 14.42.326.0

**Comment by agrieve** [comment]
Have a look here:
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library_beta/

Since there's no v14 in there, there's no value you can currently set to get v14. Maybe try asking the xwalk team to publish an alpha in there? Would be reasonable to create an "alpha" directory here:
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/ I think.

**Comment by Bnaya** [comment]
I've opened a feature request to crosswalk to made also canary version available
https://crosswalk-project.org/jira/browse/XWALK-3986
Vote it up please :)

**Comment by Hirbod** [comment]
Ha.. you were a little bit faster then me. I've also created one..

https://crosswalk-project.org/jira/browse/XWALK-3987

**Comment by Hirbod** [comment]
Dear @agrieve,

isn't it possible to find a way around it, even without crosswalk-side-changes? 
Why isn't it possible to change the link looking inside of https://download.01.org/crosswalk/releases/crosswalk/android/canary/ ?

Is this link "hardcoded" inside of cordova build script or something I did not understand clearly?

**Comment by Bnaya** [comment]
The dependencies declared inside gradle/maven file. if you have enough maven & building crosswalk by yourself knowledge you can tell maven to pull the dependencies from a local directory.
It might be more simple than its sounds but i don't really knows
