### ISSUE TITLE
Disable pull to refresh

### ISSUE THREAD

**Issue by lfrodrigues** [MobileChromeApps/cordova-plugin-crosswalk-webview#27]
I would like to disable pull to refresh. I've seen from crosswalk docs we should be able to pass 
--disable-pull-to-refresh-effect as a parameter.

Can you please tell how can this be done?

There are more people needing this here: driftyco/ionic-cli/issues/376

**Comment by lfrodrigues** [comment]
Just found the solution (after trial and error and googlefu). 

Created a file called: 
`platforms/android/assets/xwalk-command-line`
with the content:
`xwalk --disable-pull-to-refresh-effect`

**Comment by agrieve** [comment]
Published 1.2.0 of the plugin with this change

**Comment by lfrodrigues** [comment]
thanks!
