### ISSUE TITLE
Cordova Build overwrites config file

### ISSUE THREAD

**Issue by northkode** [MobileChromeApps/cordova-plugin-crosswalk-webview#29]
I can't change the cross walk version cause cordova build commands overwrites the config file everytime...

**Comment by agrieve** [comment]
v1.1.0 of the plugin added a config.xml setting for this:

    <preference name="xwalkVersion" value="..." />

**Comment by northkode** [comment]
I did... but when i do cordova build - it overwrites the preference tag and deletes it.. so the build is always using the default 13+ instead of the version I specify!

**Comment by agrieve** [comment]
Are you putting the the tag in your top-level config.xml? The platforms/android/res/xml one gets generated by the cordova tool

**Comment by northkode** [comment]
Yes, it actually overwrites the top level completely.. 
It resets it to the defaults of HelloWorld, even tho i specified a proper app name on build. 
The default app create works great, it creates the correct config.xml file with all my plugin settings.. and then cordova build completely overwrites all my files and resets the app to default config settings.

**Comment by northkode** [comment]
I figured out the problem. Grunt has a version-bump plugin to update cordova app config version numbers. This was reseting my application. Not cordova. 

Thanks for the help!
